name: pyATP
dependencies:
- python=3.4.5=0
- pip:
  - alabaster==0.7.9
  - argh==0.26.2
  - babel==2.3.4
  - bumpversion==0.5.3
  - coverage==4.1
  - docutils==0.12
  - flake8==2.6.0
  - fortranformat==0.2.5
  - imagesize==0.7.1
  - jinja2==2.8
  - markupsafe==0.23
  - mccabe==0.5.2
  - pathtools==0.1.2
  - pluggy==0.3.1
  - py==1.4.31
  - pyatp (c:\users\pdbrown\documents\python scripts\pyatp)
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - pygments==2.1.3
  - pytest==2.9.2
  - pytest-cov==2.3.0
  - pytz==2016.6.1
  - pyyaml==3.11
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sphinx==1.4.4
  - text-data-cards (/home/pdb/Development/text_data_cards)
  - tox==2.3.1
  - virtualenv==15.0.2
  - watchdog==0.8.3

